/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ASoftwareForLearning.component;

import ASoftwareForLearning.Database.forTitleAndSubjectJList;
import ASoftwareForLearning.pages.addSubject;

/**
 *
 * @author Zubai
 */
public class addSubjectPanel extends javax.swing.JPanel {

   
    forTitleAndSubjectJList subjectJlistData = new forTitleAndSubjectJList();
    
    
    public addSubjectPanel() {
        initComponents();
        
        subjectJlistData.fillDataSubjectJList(subjectJList);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddSubjectButton = new ASoftwareForLearning.component.KButton();
        addSubjectLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectJList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(0, 0, 0));

        AddSubjectButton.setText("Add Subject");
        AddSubjectButton.setkBackGroundColor(new java.awt.Color(51, 255, 51));
        AddSubjectButton.setkEndColor(new java.awt.Color(255, 102, 51));
        AddSubjectButton.setkForeGround(new java.awt.Color(0, 0, 0));
        AddSubjectButton.setkHoverEndColor(new java.awt.Color(255, 102, 51));
        AddSubjectButton.setkHoverForeGround(new java.awt.Color(51, 255, 51));
        AddSubjectButton.setkHoverStartColor(new java.awt.Color(255, 102, 51));
        AddSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubjectButtonActionPerformed(evt);
            }
        });

        addSubjectLabel.setBackground(new java.awt.Color(255, 255, 255));
        addSubjectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addSubjectLabel.setForeground(new java.awt.Color(0, 0, 0));
        addSubjectLabel.setText("Subjects");

        jScrollPane1.setViewportView(subjectJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AddSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSubjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubjectButtonActionPerformed
        // TODO add your handling code here:
        addSubject subjectFrame = new addSubject();
        subjectFrame.setVisible(true);
    }//GEN-LAST:event_AddSubjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ASoftwareForLearning.component.KButton AddSubjectButton;
    private javax.swing.JLabel addSubjectLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> subjectJList;
    // End of variables declaration//GEN-END:variables

}
