    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ASoftwareForLearning.component;

import ASoftwareForLearning.Database.forTitleAndSubjectJList;
import ASoftwareForLearning.pages.addTitle;

/**
 *
 * @author Zubai
 */
public class AddTitlePanel extends javax.swing.JPanel {

    
    forTitleAndSubjectJList titleJlistData = new forTitleAndSubjectJList();
    
    private String selectedTitle;
    
    
    public AddTitlePanel() {
        initComponents();
        titleJlistData.fillDataTitleJList(titleJList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleJList = new javax.swing.JList<>();
        AddTitleButton = new ASoftwareForLearning.component.KButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(250, 250));
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(250, 250));

        addTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        addTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        addTitleLabel.setText("Titles");

        titleJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(titleJList);

        AddTitleButton.setText("Add Title");
        AddTitleButton.setkBackGroundColor(new java.awt.Color(51, 255, 51));
        AddTitleButton.setkEndColor(new java.awt.Color(255, 102, 51));
        AddTitleButton.setkForeGround(new java.awt.Color(0, 0, 0));
        AddTitleButton.setkHoverEndColor(new java.awt.Color(255, 102, 51));
        AddTitleButton.setkHoverForeGround(new java.awt.Color(51, 255, 51));
        AddTitleButton.setkHoverStartColor(new java.awt.Color(255, 102, 51));
        AddTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTitleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AddTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTitleButtonActionPerformed
        // TODO add your handling code here:
        
        addTitle titleframe = new addTitle();
        titleframe.setVisible(true);
        
    }//GEN-LAST:event_AddTitleButtonActionPerformed

    private void titleJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleJListMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_titleJListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ASoftwareForLearning.component.KButton AddTitleButton;
    private javax.swing.JLabel addTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> titleJList;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the selectedTitle
     */
    public String getSelectedTitle() {
        return selectedTitle;
    }
}
