
package ASoftwareForLearning.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class RecentlyAddedQuestionsList extends javax.swing.JPanel {

    /**
     * Creates new form RecentlyAddedQuestionsList
     */
    public RecentlyAddedQuestionsList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recentCards = new javax.swing.JScrollPane();

        setMaximumSize(new java.awt.Dimension(270, 520));
        setMinimumSize(new java.awt.Dimension(270, 520));
        setPreferredSize(new java.awt.Dimension(270, 520));

        recentCards.setBorder(null);
        recentCards.setMaximumSize(new java.awt.Dimension(520, 270));
        recentCards.setMinimumSize(new java.awt.Dimension(520, 270));
        recentCards.setOpaque(false);
        recentCards.setPreferredSize(new java.awt.Dimension(520, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(recentCards, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentCards, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        Color color1 = new Color(0, 255, 135);
        Color color2 = new Color(96, 239, 255);
        GradientPaint gp = new GradientPaint(0, 0, color1, w, h, color2);
        g2d.setPaint(gp);
        g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane recentCards;
    // End of variables declaration//GEN-END:variables
}
