/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ASoftwareForLearning.pages;

import ASoftwareForLearning.Database.addSubjectFromFrame;

/**
 *
 * @author Zubai
 */
public class addSubject extends javax.swing.JFrame {

    /**
     * Creates new form addTitle
     */
    public addSubject() {
        initComponents();
        
        TitleAddTxtField.setLabelText("Subject");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new ASoftwareForLearning.swing.PanelBorder();
        TitleAddTxtField = new ASoftwareForLearning.InputPageComponents.TextField();
        addTitleButton = new ASoftwareForLearning.component.KButton();
        CloseButtonAddTitle = new ASoftwareForLearning.component.KButton();
        subjectSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setForeground(new java.awt.Color(0, 0, 0));

        TitleAddTxtField.setBackground(new java.awt.Color(255, 255, 255));
        TitleAddTxtField.setForeground(new java.awt.Color(0, 0, 0));

        addTitleButton.setText("Add");
        addTitleButton.setkBackGroundColor(new java.awt.Color(0, 255, 255));
        addTitleButton.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        addTitleButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        addTitleButton.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        addTitleButton.setkSelectedColor(new java.awt.Color(102, 102, 102));
        addTitleButton.setPreferredSize(new java.awt.Dimension(72, 23));
        addTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleButtonActionPerformed(evt);
            }
        });

        CloseButtonAddTitle.setText("Cancel");
        CloseButtonAddTitle.setkBackGroundColor(new java.awt.Color(0, 255, 255));
        CloseButtonAddTitle.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        CloseButtonAddTitle.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        CloseButtonAddTitle.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        CloseButtonAddTitle.setPreferredSize(new java.awt.Dimension(72, 23));
        CloseButtonAddTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonAddTitleActionPerformed(evt);
            }
        });

        subjectSuccess.setBackground(new java.awt.Color(255, 255, 255));
        subjectSuccess.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleAddTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(CloseButtonAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(addTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(subjectSuccess)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TitleAddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(subjectSuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButtonAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonAddTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonAddTitleActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseButtonAddTitleActionPerformed

    private void addTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleButtonActionPerformed
        // TODO add your handling code here:
        addSubjectFromFrame add = new addSubjectFromFrame();
        String Subject = TitleAddTxtField.getText();
        add.addSubject(Subject);
        
        
        
        
        
    }//GEN-LAST:event_addTitleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ASoftwareForLearning.component.KButton CloseButtonAddTitle;
    private ASoftwareForLearning.InputPageComponents.TextField TitleAddTxtField;
    private ASoftwareForLearning.component.KButton addTitleButton;
    private ASoftwareForLearning.swing.PanelBorder panelBorder1;
    public static javax.swing.JLabel subjectSuccess;
    // End of variables declaration//GEN-END:variables
}
