
package ASoftwareForLearning.pages;

import ASoftwareForLearning.Database.ComboBox;
import ASoftwareForLearning.Database.addTitleFromFrame;
import javax.swing.JOptionPane;

public class addTitle extends javax.swing.JFrame {

    ComboBox subjectBox = new ComboBox();
    
    
    public addTitle() {
        initComponents();
        
        TitleAddTxtField.setLabelText("Title");
        
        //for comboBox
        subjectBox.fillSubjectForTitle(comboboxForTitles);
        
        comboboxForTitles.setLabeText("Subject");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new ASoftwareForLearning.swing.PanelBorder();
        addTitleButton = new ASoftwareForLearning.component.KButton();
        CloseButtonAddTitle = new ASoftwareForLearning.component.KButton();
        TitleAddTxtField = new ASoftwareForLearning.InputPageComponents.TextField();
        comboboxForTitles = new ASoftwareForLearning.component.Combobox();
        TitleSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setForeground(new java.awt.Color(0, 0, 0));

        addTitleButton.setText("Add");
        addTitleButton.setkBackGroundColor(new java.awt.Color(0, 255, 255));
        addTitleButton.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        addTitleButton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        addTitleButton.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        addTitleButton.setkSelectedColor(new java.awt.Color(102, 102, 102));
        addTitleButton.setPreferredSize(new java.awt.Dimension(72, 23));
        addTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleButtonActionPerformed(evt);
            }
        });

        CloseButtonAddTitle.setText("Cancel");
        CloseButtonAddTitle.setkBackGroundColor(new java.awt.Color(204, 204, 0));
        CloseButtonAddTitle.setkEndColor(new java.awt.Color(204, 204, 0));
        CloseButtonAddTitle.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        CloseButtonAddTitle.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        CloseButtonAddTitle.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        CloseButtonAddTitle.setkSelectedColor(new java.awt.Color(102, 102, 102));
        CloseButtonAddTitle.setkStartColor(new java.awt.Color(204, 204, 0));
        CloseButtonAddTitle.setPreferredSize(new java.awt.Dimension(72, 23));
        CloseButtonAddTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonAddTitleActionPerformed(evt);
            }
        });

        TitleAddTxtField.setBackground(new java.awt.Color(255, 255, 255));
        TitleAddTxtField.setForeground(new java.awt.Color(0, 0, 0));

        comboboxForTitles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxForTitlesActionPerformed(evt);
            }
        });

        TitleSuccess.setBackground(new java.awt.Color(255, 255, 255));
        TitleSuccess.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleAddTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxForTitles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(CloseButtonAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(addTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(TitleSuccess)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TitleAddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboboxForTitles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(TitleSuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseButtonAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxForTitlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxForTitlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxForTitlesActionPerformed

    private void addTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleButtonActionPerformed
        // TODO add your handling code here:
        addTitleFromFrame add = new addTitleFromFrame();
        
        if(TitleAddTxtField.getText() == ""){
            JOptionPane.showMessageDialog(null, "Enter a valid name");
        }else{
        
        add.addTitle(TitleAddTxtField.getText(), comboboxForTitles.getSelectedItem().toString());
        
        
        }
        
        new ComboBox().fillTitleForQuestion(ASoftwareForLearning.pages.Input.comboForQuestions);
        
        
        
        
        TitleAddTxtField.setText("");
        TitleAddTxtField.requestFocus();
        
    }//GEN-LAST:event_addTitleButtonActionPerformed

    private void CloseButtonAddTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonAddTitleActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseButtonAddTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTitle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ASoftwareForLearning.component.KButton CloseButtonAddTitle;
    private ASoftwareForLearning.InputPageComponents.TextField TitleAddTxtField;
    public static javax.swing.JLabel TitleSuccess;
    private ASoftwareForLearning.component.KButton addTitleButton;
    private ASoftwareForLearning.component.Combobox comboboxForTitles;
    private ASoftwareForLearning.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
