/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ASoftwareForLearning.pages;

import ASoftwareForLearning.App;


public class Home extends javax.swing.JPanel {

    Study study = new Study();
 
    public Home() {
        initComponents();
        statistics1.setVisible(false);
        questions1.setVisible(false);
        subjects1.setVisible(false);
        titles1.setVisible(false);
        studyButton.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notes1 = new ASoftwareForLearning.TODO.Notes();
        addTitlePanel1 = new ASoftwareForLearning.component.AddTitlePanel();
        graph1 = new ASoftwareForLearning.component.Graph();
        addSubjectPanel1 = new ASoftwareForLearning.component.addSubjectPanel();
        studyButton = new ASoftwareForLearning.component.KButton();
        homePanel2 = new ASoftwareForLearning.component.HomePanel();
        statistics1 = new ASoftwareForLearning.pages.Statistics();
        questions1 = new ASoftwareForLearning.pages.Questions();
        subjects1 = new ASoftwareForLearning.pages.Subjects();
        titles1 = new ASoftwareForLearning.pages.Titles();
        header1 = new ASoftwareForLearning.component.Header();

        setMaximumSize(new java.awt.Dimension(1190, 590));
        setMinimumSize(new java.awt.Dimension(1190, 590));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1190, 590));
        setLayout(null);

        notes1.setBackground(new java.awt.Color(204, 204, 204));
        notes1.setForeground(new java.awt.Color(0, 0, 0));
        notes1.setOpaque(false);

        javax.swing.GroupLayout notes1Layout = new javax.swing.GroupLayout(notes1);
        notes1.setLayout(notes1Layout);
        notes1Layout.setHorizontalGroup(
            notes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notes1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addTitlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        notes1Layout.setVerticalGroup(
            notes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTitlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(notes1);
        notes1.setBounds(10, 60, 250, 250);

        graph1.setBackground(new java.awt.Color(204, 204, 204));
        graph1.setForeground(new java.awt.Color(0, 0, 0));
        graph1.setMaximumSize(new java.awt.Dimension(250, 250));
        graph1.setMinimumSize(new java.awt.Dimension(250, 250));
        graph1.setOpaque(false);
        graph1.setPreferredSize(new java.awt.Dimension(250, 250));
        graph1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graph1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graph1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addSubjectPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graph1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSubjectPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(graph1);
        graph1.setBounds(10, 320, 250, 260);

        studyButton.setBackground(new java.awt.Color(255, 255, 255));
        studyButton.setForeground(new java.awt.Color(0, 0, 0));
        studyButton.setText("Study");
        studyButton.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        studyButton.setkBorderRadius(25);
        studyButton.setkForeGround(new java.awt.Color(0, 0, 0));
        studyButton.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        studyButton.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        studyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyButtonActionPerformed(evt);
            }
        });
        add(studyButton);
        studyButton.setBounds(270, 320, 650, 260);

        homePanel2.setOpaque(false);
        add(homePanel2);
        homePanel2.setBounds(270, 60, 910, 520);
        add(statistics1);
        statistics1.setBounds(270, 60, 910, 520);

        questions1.setBackground(new java.awt.Color(255, 255, 255));
        add(questions1);
        questions1.setBounds(270, 60, 910, 520);

        subjects1.setBackground(new java.awt.Color(255, 255, 255));
        subjects1.setForeground(new java.awt.Color(0, 0, 0));
        add(subjects1);
        subjects1.setBounds(270, 60, 910, 520);

        titles1.setBackground(new java.awt.Color(255, 255, 255));
        titles1.setForeground(new java.awt.Color(0, 0, 0));
        add(titles1);
        titles1.setBounds(270, 60, 910, 520);
        add(header1);
        header1.setBounds(10, 10, 1180, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void graph1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph1MousePressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_graph1MousePressed

    private void graph1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph1MouseClicked
        // TODO add your handling code here:
//        titles1.setVisible(false);
//        subjects1.setVisible(false);
//        questions1.setVisible(false);
//        homePanel2.setVisible(false);
//        statistics1.setVisible(true);
//        studyButton.setVisible(false);
    }//GEN-LAST:event_graph1MouseClicked

    private void studyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyButtonActionPerformed
        // TODO add your handling code here:
        
        ASoftwareForLearning.App.study1.setVisible(true);
        ASoftwareForLearning.App.homePage1.setVisible(false);
        
       
        
       
        
        
    }//GEN-LAST:event_studyButtonActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ASoftwareForLearning.component.addSubjectPanel addSubjectPanel1;
    private ASoftwareForLearning.component.AddTitlePanel addTitlePanel1;
    private ASoftwareForLearning.component.Graph graph1;
    public static ASoftwareForLearning.component.Header header1;
    public static ASoftwareForLearning.component.HomePanel homePanel2;
    private ASoftwareForLearning.TODO.Notes notes1;
    public static ASoftwareForLearning.pages.Questions questions1;
    public static ASoftwareForLearning.pages.Statistics statistics1;
    public static ASoftwareForLearning.component.KButton studyButton;
    public static ASoftwareForLearning.pages.Subjects subjects1;
    public static ASoftwareForLearning.pages.Titles titles1;
    // End of variables declaration//GEN-END:variables
}
